export const MODEL_CATALOG = [
    {
        id: 'SmolLM2-135M-Instruct-q0f16-MLC',
        name: 'SmolLM2 - 135M',
        size: '~110MB',
        vramMB: 300,
        tier: 'nano',
        desc: 'Tiny fallback model for low-memory devices.',
    },
    {
        id: 'SmolLM2-360M-Instruct-q0f16-MLC',
        name: 'SmolLM2 - 360M',
        size: '~200MB',
        vramMB: 400,
        tier: 'nano',
        desc: 'Ultra-fast, minimal footprint. Basic chat only.',
    },
    {
        id: 'Qwen3-0.6B-q4f16_1-MLC',
        name: 'Qwen 3 - 0.6B',
        size: '~400MB',
        vramMB: 600,
        tier: 'lite',
        thinking: true,
        desc: 'Fast and lightweight. Better reasoning than Qwen2.5-0.5B.',
    },
    {
        id: 'Llama-3.2-1B-Instruct-q4f16_1-MLC',
        name: 'Llama 3.2 - 1B',
        size: '~750MB',
        vramMB: 900,
        tier: 'lite',
        desc: 'Balanced small model with solid general chat quality.',
    },
    {
        id: 'SmolLM2-1.7B-Instruct-q4f16_1-MLC',
        name: 'SmolLM2 - 1.7B',
        size: '~1GB',
        vramMB: 1200,
        tier: 'standard',
        desc: 'HuggingFace\'s efficient small model. Good for its size.',
    },
    {
        id: 'Qwen3-1.7B-q4f16_1-MLC',
        name: 'Qwen 3 - 1.7B',
        size: '~1.1GB',
        vramMB: 1500,
        tier: 'standard',
        thinking: true,
        desc: 'Great balance of speed and intelligence. Thinking mode.',
    },
    {
        id: 'Llama-3.2-3B-Instruct-q4f16_1-MLC',
        name: 'Llama 3.2 - 3B',
        size: '~2GB',
        vramMB: 2500,
        tier: 'performance',
        desc: 'Meta\'s compact model. Reliable all-rounder.',
    },
    {
        id: 'Qwen3-4B-q4f16_1-MLC',
        name: 'Qwen 3 - 4B',
        size: '~2.5GB',
        vramMB: 3500,
        tier: 'performance',
        thinking: true,
        desc: 'Best value. Matches larger models on reasoning tasks.',
    },
    {
        id: 'Phi-3.5-mini-instruct-q4f16_1-MLC',
        name: 'Phi 3.5 Mini - 3.8B',
        size: '~2.4GB',
        vramMB: 3500,
        tier: 'performance',
        desc: 'Microsoft\'s model. Strong at math and logic.',
    },
    {
        id: 'Phi-3.5-vision-instruct-q4f16_1-MLC',
        name: 'Phi 3.5 Vision - 4.2B',
        size: '~2.7GB',
        vramMB: 4000,
        tier: 'vision',
        vision: true,
        desc: 'Can understand images! Describe, read text, answer questions about photos.',
    },
    {
        id: 'DeepSeek-R1-Distill-Qwen-7B-q4f16_1-MLC',
        name: 'DeepSeek R1 Distill - 7B',
        size: '~4.5GB',
        vramMB: 5500,
        tier: 'premium',
        thinking: true,
        desc: 'DeepSeek R1 reasoning distilled into 7B. Top-tier thinking.',
    },
    {
        id: 'Qwen3-8B-q4f16_1-MLC',
        name: 'Qwen 3 - 8B',
        size: '~5GB',
        vramMB: 6000,
        tier: 'premium',
        thinking: true,
        desc: 'Best quality. Strong reasoning + thinking mode. Needs 6GB+ VRAM.',
    },
    {
        id: 'gemma-2-2b-it-q4f16_1-MLC',
        name: 'Gemma 2 - 2B',
        size: '~1.7GB',
        vramMB: 2200,
        tier: 'performance',
        advanced: true,
        desc: 'Advanced family option tuned for instruction following.',
    },
    {
        id: 'Mistral-7B-Instruct-v0.3-q4f16_1-MLC',
        name: 'Mistral 7B Instruct v0.3',
        size: '~4.4GB',
        vramMB: 5500,
        tier: 'premium',
        advanced: true,
        desc: 'Advanced instruct-tuned 7B model.',
    },
    {
        id: 'OpenHermes-2.5-Mistral-7B-q4f16_1-MLC',
        name: 'OpenHermes 2.5 - Mistral 7B',
        size: '~4.4GB',
        vramMB: 5500,
        tier: 'premium',
        advanced: true,
        desc: 'Advanced conversational Mistral 7B variant.',
    },
    {
        id: 'NeuralHermes-2.5-Mistral-7B-q4f16_1-MLC',
        name: 'NeuralHermes 2.5 - Mistral 7B',
        size: '~4.4GB',
        vramMB: 5500,
        tier: 'premium',
        advanced: true,
        desc: 'Advanced alternative tuned for assistant-style chat.',
    },
    {
        id: 'Hermes-2-Pro-Llama-3-8B-q4f16_1-MLC',
        name: 'Hermes 2 Pro - Llama 3 8B',
        size: '~5.1GB',
        vramMB: 6200,
        tier: 'premium',
        advanced: true,
        desc: 'Advanced Llama 8B family variant.',
    },
    {
        id: 'Hermes-3-Llama-3.1-8B-q4f16_1-MLC',
        name: 'Hermes 3 - Llama 3.1 8B',
        size: '~5.1GB',
        vramMB: 6200,
        tier: 'premium',
        advanced: true,
        desc: 'Advanced Hermes 3 model for experimentation.',
    },
    {
        id: 'DeepSeek-R1-Distill-Llama-8B-q4f16_1-MLC',
        name: 'DeepSeek R1 Distill - Llama 8B',
        size: '~5.3GB',
        vramMB: 6500,
        tier: 'premium',
        thinking: true,
        advanced: true,
        desc: 'Advanced reasoning-focused Llama 8B distill.',
    },
    {
        id: 'gemma-2-9b-it-q4f16_1-MLC',
        name: 'Gemma 2 - 9B',
        size: '~5.8GB',
        vramMB: 7000,
        tier: 'premium',
        advanced: true,
        desc: 'Large advanced Gemma model, requires high VRAM.',
    },
];
